// Tool for extracting platform-specific sizes and constants from duktape.h.
// To use:
//
//   gcc -I../duktape/src -o generate generate.c
//   ./generate > generated.rs

#include <stdio.h>
#include "duktape.h"

// Translate types to Rust.
#define INT_TYPE(TYPE) \
    printf("pub type %s = %s%lu;\n", #TYPE, ((TYPE) -1) > 0 ? "u" : "i", \
           8*sizeof(TYPE));

// Convert typedefs to constants.
#define CONST_L(TYPE, NAME) \
    printf("pub const %s: %s = %ld;\n", #NAME, #TYPE, NAME)
#define CONST(TYPE, NAME) \
    printf("pub const %s: %s = %d;\n", #NAME, #TYPE, NAME)

int main(int argc, char **argv) {
    // File header.
    printf("//! Platform-specific values generated by defgen.c.\n\n");
    printf("use libc::types::os::arch::c95::{c_long, c_double};\n\n");

    // Print type declarations.
    INT_TYPE(duk_errcode_t);
    INT_TYPE(duk_idx_t);
    INT_TYPE(duk_int_t);
    INT_TYPE(duk_ret_t);
    INT_TYPE(duk_uint_t);
    INT_TYPE(duk_bool_t);
    INT_TYPE(duk_uarridx_t);
    INT_TYPE(duk_codepoint_t);
    INT_TYPE(duk_ucodepoint_t);
    INT_TYPE(duk_size_t);
    INT_TYPE(duk_ptrdiff_t);
    INT_TYPE(duk_int32_t);
    INT_TYPE(duk_uint32_t);
    INT_TYPE(duk_uint16_t);
    printf("pub type duk_double_t = c_double;\n");

    // This is an integer with an "L" specifier.
    CONST_L(c_long, DUK_VERSION);
    CONST(duk_idx_t, DUK_INVALID_INDEX);
    CONST(duk_int_t, DUK_VARARGS);
    // This type is fairly arbitrary: It's small and non-negative, and I
    // can't find any place in the API which would take it.
    CONST(duk_idx_t, DUK_API_ENTRY_STACK);
    CONST(duk_int_t, DUK_TYPE_NONE);
    CONST(duk_int_t, DUK_TYPE_UNDEFINED);
    CONST(duk_int_t, DUK_TYPE_NULL);
    CONST(duk_int_t, DUK_TYPE_BOOLEAN);
    CONST(duk_int_t, DUK_TYPE_NUMBER);
    CONST(duk_int_t, DUK_TYPE_STRING);
    CONST(duk_int_t, DUK_TYPE_OBJECT);
    CONST(duk_int_t, DUK_TYPE_BUFFER);
    CONST(duk_int_t, DUK_TYPE_POINTER);
    CONST(duk_uint_t, DUK_TYPE_MASK_NONE);
    CONST(duk_uint_t, DUK_TYPE_MASK_UNDEFINED);
    CONST(duk_uint_t, DUK_TYPE_MASK_NULL);
    CONST(duk_uint_t, DUK_TYPE_MASK_BOOLEAN);
    CONST(duk_uint_t, DUK_TYPE_MASK_NUMBER);
    CONST(duk_uint_t, DUK_TYPE_MASK_STRING);
    CONST(duk_uint_t, DUK_TYPE_MASK_OBJECT);
    CONST(duk_uint_t, DUK_TYPE_MASK_BUFFER);
    CONST(duk_uint_t, DUK_TYPE_MASK_POINTER);
    CONST(duk_uint_t, DUK_TYPE_MASK_THROW);
    CONST(duk_int_t, DUK_HINT_NONE);
    CONST(duk_int_t, DUK_HINT_STRING);
    CONST(duk_int_t, DUK_HINT_NUMBER);
    CONST(duk_uint_t, DUK_ENUM_INCLUDE_NONENUMERABLE);
    CONST(duk_uint_t, DUK_ENUM_INCLUDE_INTERNAL);
    CONST(duk_uint_t, DUK_ENUM_OWN_PROPERTIES_ONLY);
    CONST(duk_uint_t, DUK_ENUM_ARRAY_INDICES_ONLY);
    CONST(duk_uint_t, DUK_ENUM_SORT_ARRAY_INDICES);
    CONST(duk_uint_t, DUK_ENUM_NO_PROXY_BEHAVIOR);
    CONST(duk_uint_t, DUK_COMPILE_EVAL);
    CONST(duk_uint_t, DUK_COMPILE_FUNCTION);
    CONST(duk_uint_t, DUK_COMPILE_STRICT);
    CONST(duk_uint_t, DUK_COMPILE_SAFE);
    CONST(duk_uint_t, DUK_COMPILE_NORESULT);
    CONST(duk_uint_t, DUK_COMPILE_NOSOURCE);
    CONST(duk_uint_t, DUK_COMPILE_STRLEN);
    CONST(duk_uint_t, DUK_THREAD_NEW_GLOBAL_ENV);
    CONST(duk_uint_t, DUK_STRING_PUSH_SAFE);
    CONST(duk_errcode_t, DUK_ERR_UNIMPLEMENTED_ERROR);
    CONST(duk_errcode_t, DUK_ERR_UNSUPPORTED_ERROR);
    CONST(duk_errcode_t, DUK_ERR_INTERNAL_ERROR);
    CONST(duk_errcode_t, DUK_ERR_ALLOC_ERROR);
    CONST(duk_errcode_t, DUK_ERR_ASSERTION_ERROR);
    CONST(duk_errcode_t, DUK_ERR_API_ERROR);
    CONST(duk_errcode_t, DUK_ERR_UNCAUGHT_ERROR);
    CONST(duk_errcode_t, DUK_ERR_ERROR);
    CONST(duk_errcode_t, DUK_ERR_EVAL_ERROR);
    CONST(duk_errcode_t, DUK_ERR_RANGE_ERROR);
    CONST(duk_errcode_t, DUK_ERR_REFERENCE_ERROR);
    CONST(duk_errcode_t, DUK_ERR_SYNTAX_ERROR);
    CONST(duk_errcode_t, DUK_ERR_TYPE_ERROR);
    CONST(duk_errcode_t, DUK_ERR_URI_ERROR);
    CONST(duk_ret_t, DUK_RET_UNIMPLEMENTED_ERROR);
    CONST(duk_ret_t, DUK_RET_UNSUPPORTED_ERROR);
    CONST(duk_ret_t, DUK_RET_INTERNAL_ERROR);
    CONST(duk_ret_t, DUK_RET_ALLOC_ERROR);
    CONST(duk_ret_t, DUK_RET_ASSERTION_ERROR);
    CONST(duk_ret_t, DUK_RET_API_ERROR);
    CONST(duk_ret_t, DUK_RET_UNCAUGHT_ERROR);
    CONST(duk_ret_t, DUK_RET_ERROR);
    CONST(duk_ret_t, DUK_RET_EVAL_ERROR);
    CONST(duk_ret_t, DUK_RET_RANGE_ERROR);
    CONST(duk_ret_t, DUK_RET_REFERENCE_ERROR);
    CONST(duk_ret_t, DUK_RET_SYNTAX_ERROR);
    CONST(duk_ret_t, DUK_RET_TYPE_ERROR);
    CONST(duk_ret_t, DUK_RET_URI_ERROR);
    // TODO: Double-check type of DUK_EXEC_*.
    CONST(duk_int_t, DUK_EXEC_SUCCESS);
    CONST(duk_int_t, DUK_EXEC_ERROR);
    CONST(duk_int_t, DUK_LOG_TRACE);
    CONST(duk_int_t, DUK_LOG_DEBUG);
    CONST(duk_int_t, DUK_LOG_INFO);
    CONST(duk_int_t, DUK_LOG_WARN);
    CONST(duk_int_t, DUK_LOG_ERROR);
    CONST(duk_int_t, DUK_LOG_FATAL);

    return 0;
}
